services:
  scpsl:
    image: scpsl
    container_name: scp
    restart: unless-stopped
    volumes:
      - ./config:/config
    user: scpsl
    # TODO use iptables instead of host network
    # do not use this in production
    network_mode: host