services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/ssl
    restart: unless-stopped
