services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 10G
      MAX_MEMORY: 40G
      TYPE: "PAPER"
      VERSION: "1.20.6"
    volumes:
      - ./data:/data
    # TODO use iptables instead of host network
    # do not use this in production
    network_mode: host
    restart: unless-stopped
    