services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 10G
      MAX_MEMORY: 40G
      TYPE: "PAPER"
      VERSION: "1.20.6"
    volumes:
      - ./data:/data
    ports:
      - "25565:25565"
      - "25575:25575"
    restart: unless-stopped
    stdin_open: true
    tty: true